#!/bin/bash

python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 0 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 1 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 2 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 3 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 4 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 5 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 6 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 7 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 8 --world-size 10 --backend ccl &
python3 fed_train_homogeneous_basic.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/no_channel/K=1 --disable_cut_edges --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 500 --n_kernel 16 --rank 9 --world-size 10 --backend ccl &
