#!/bin/bash

python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 0 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 1 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 2 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 3 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 4 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 5 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 6 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 7 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 8 --world-size 10 --backend ccl &
python3 train_homogeneous_graph_advanced.py --partitioning-json-file ../partition_data/ogbn-arxiv.json         --log_dir log/fixed_channel/node/CR=4/K=1 --compression_type node --comp_ratio 4 --enable_cr --train-mode one_shot_aggregation --ip-file ip_file.txt --fed_agg_round 1 --lr 1e-3             --train-iters 512 --rank 9 --world-size 10 --backend ccl &
wait
